version: '4.20.1'
services:
  php-apache-environment:
    container_name: php-apache
    build:
      context: ./php
      dockerfile: 'C:\Users\Amin\Desktop\stage\music-action\php\src\Dockerfile.yml'
    depends_on:
      - db
    volumes:
      - 'C:\Users\Amin\Desktop\stage\music-action\php\src:/var/www/html'
    ports:
      - 8000:80

  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: stage2023
      MYSQL_DATABASE: music-action
      MYSQL_USER: amin@music-action.com
      MYSQL_PASSWORD: stage2023
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - '8080:80'
    restart: always
    environment:
        PMA_HOST: db
    depends_on:
        - db